# Generated by Django 4.2.14 on 2024-07-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0003_cronjoblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjoblog',
            options={'get_latest_by': 'start_time'},
        ),
        migrations.RenameIndex(
            model_name='cronjoblog',
            new_name='django_cron_code_966ed3_idx',
            old_fields=('code', 'start_time'),
        ),
        migrations.RenameIndex(
            model_name='cronjoblog',
            new_name='django_cron_code_21f381_idx',
            old_fields=('code', 'start_time', 'ran_at_time'),
        ),
        migrations.RenameIndex(
            model_name='cronjoblog',
            new_name='django_cron_code_89ad04_idx',
            old_fields=('code', 'is_success', 'ran_at_time'),
        ),
        migrations.AlterField(
            model_name='cronjoblog',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cronjoblog',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cronjoblog',
            name='ran_at_time',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cronjoblog',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='cronjoblog',
            index=models.Index(fields=['code'], name='django_cron_code_26aea9_idx'),
        ),
        migrations.AddIndex(
            model_name='cronjoblog',
            index=models.Index(fields=['start_time'], name='django_cron_start_t_9e0b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='cronjoblog',
            index=models.Index(fields=['end_time'], name='django_cron_end_tim_c3cfdc_idx'),
        ),
        migrations.AddIndex(
            model_name='cronjoblog',
            index=models.Index(fields=['ran_at_time'], name='django_cron_ran_at__aa3be6_idx'),
        ),
    ]
